# 1. IMDB 리뷰 데이터를 훈련 데이터로 사용하기

cmd에서 conda install -c pytorch torchtext로 설치

In [14]:
from torchtext.legacy import data, datasets
TEXT = data.Field(sequential=True, batch_first=True, lower=True)
LABEL = data.Field(sequential=False, batch_first=True)

In [18]:
trainset, testset = datasets.IMDB.splits(TEXT, LABEL, root = 'A:\chchdata\data')

downloading aclImdb_v1.tar.gz


A:\chchdata\data\imdb\aclImdb_v1.tar.gz: 100%|██████████| 84.1M/84.1M [00:56<00:00, 1.48MB/s]


In [19]:
print('훈련 데이터의 크기 : {}' .format(len(trainset)))

훈련 데이터의 크기 : 25000


In [21]:
print(vars(trainset[1]))

{'text': ['homelessness', '(or', 'houselessness', 'as', 'george', 'carlin', 'stated)', 'has', 'been', 'an', 'issue', 'for', 'years', 'but', 'never', 'a', 'plan', 'to', 'help', 'those', 'on', 'the', 'street', 'that', 'were', 'once', 'considered', 'human', 'who', 'did', 'everything', 'from', 'going', 'to', 'school,', 'work,', 'or', 'vote', 'for', 'the', 'matter.', 'most', 'people', 'think', 'of', 'the', 'homeless', 'as', 'just', 'a', 'lost', 'cause', 'while', 'worrying', 'about', 'things', 'such', 'as', 'racism,', 'the', 'war', 'on', 'iraq,', 'pressuring', 'kids', 'to', 'succeed,', 'technology,', 'the', 'elections,', 'inflation,', 'or', 'worrying', 'if', "they'll", 'be', 'next', 'to', 'end', 'up', 'on', 'the', 'streets.<br', '/><br', '/>but', 'what', 'if', 'you', 'were', 'given', 'a', 'bet', 'to', 'live', 'on', 'the', 'streets', 'for', 'a', 'month', 'without', 'the', 'luxuries', 'you', 'once', 'had', 'from', 'a', 'home,', 'the', 'entertainment', 'sets,', 'a', 'bathroom,', 'pictures', 'on

In [22]:
from gensim.models import KeyedVectors
word2vec_model = KeyedVectors.load_word2vec_format('eng_w2v')
print(word2vec_model['this']) # 영어 단어 'this'의 임베딩 벡터값 출력

[-1.0787851  -1.4595797  -1.6951938  -1.0677129  -0.8161876   1.3518329
 -0.51005715  0.42380157 -0.929293    0.71384245  0.55134183  1.0590829
 -1.0150629  -0.03434338 -0.5499928   0.62797153  1.6568526   1.9338495
  0.8115232   0.00942545  0.22666831  1.0393754   1.7679064   1.3355246
  1.2987968  -1.9730322  -0.95621836  0.08263141 -0.30471653 -0.26669192
  1.6205046   0.5179874   0.42467242 -2.4076445   1.0491213  -1.2095188
 -0.7935057  -0.2901258   0.945805   -1.8697681  -0.47169968 -2.4670858
 -1.1096776  -0.74332905  0.02778058 -2.0888884  -1.3114471   1.4873964
  1.5078093  -2.0408823  -1.0439715   0.8034587   0.1026743   0.07208035
 -0.21107897 -0.66714126  0.29496312  0.01941346 -0.6947807   1.7927777
 -0.3508396   1.190273    0.70112103 -0.37626263 -2.3530893  -0.46349883
 -1.1945626   0.2383219  -0.23746352 -0.07986329  0.03753169  0.5586949
 -1.7013954   2.0230076  -0.13451375 -0.03937571 -0.4343432  -1.0143398
  0.33852136  0.1052811  -0.2808158  -0.47010344  1.1724986  

# 2. 사전 훈련된 Word2Vec을 초기 임베딩으로 사용하기

In [23]:
import torch
import torch.nn as nn
from torchtext.vocab import Vectors

In [24]:
vectors = Vectors(name="eng_w2v") # 사전 훈련된 Word2Vec 모델을 vectors에 저장

100%|██████████| 21613/21613 [00:00<00:00, 27360.28it/s]


In [25]:
TEXT.build_vocab(trainset, vectors=vectors, max_size=10000, min_freq=10) # Word2Vec 모델을 임베딩 벡터값으로 초기화

* max_size와 min_freq는 몇 개의 단어들만을 가지고 단어 집합을 생성할 것인지를 정합니다. max_size는 단어 집합의 크기를 제한하고, min_freq=10은 등장 빈도수가 10번 이상인 단어만 허용하는 것한다는 의미입니다.  
* vectors=vectors는 만들어진 단어 집합의 각 단어의 임베딩 벡터값으로 env_w2v에 저장되어져 있던 임베딩 벡터값들로 초기화합니다

In [32]:
# print(TEXT.vocab.stoi)

In [33]:
print(TEXT.vocab.vectors[0]) # <unk>의 임베딩 벡터값

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])


In [34]:
print(TEXT.vocab.vectors[1]) # <pad>의 임베딩 벡터값

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])


unk와 pad의 임베딩 백터값이 0으로 초기화된다.

In [35]:
embedding_layer = nn.Embedding.from_pretrained(TEXT.vocab.vectors, freeze=False)

In [36]:
print(embedding_layer(torch.LongTensor([10]))) # 단어 this의 임베딩 벡터값

tensor([[-1.0788, -1.4596, -1.6952, -1.0677, -0.8162,  1.3518, -0.5101,  0.4238,
         -0.9293,  0.7138,  0.5513,  1.0591, -1.0151, -0.0343, -0.5500,  0.6280,
          1.6569,  1.9338,  0.8115,  0.0094,  0.2267,  1.0394,  1.7679,  1.3355,
          1.2988, -1.9730, -0.9562,  0.0826, -0.3047, -0.2667,  1.6205,  0.5180,
          0.4247, -2.4076,  1.0491, -1.2095, -0.7935, -0.2901,  0.9458, -1.8698,
         -0.4717, -2.4671, -1.1097, -0.7433,  0.0278, -2.0889, -1.3114,  1.4874,
          1.5078, -2.0409, -1.0440,  0.8035,  0.1027,  0.0721, -0.2111, -0.6671,
          0.2950,  0.0194, -0.6948,  1.7928, -0.3508,  1.1903,  0.7011, -0.3763,
         -2.3531, -0.4635, -1.1946,  0.2383, -0.2375, -0.0799,  0.0375,  0.5587,
         -1.7014,  2.0230, -0.1345, -0.0394, -0.4343, -1.0143,  0.3385,  0.1053,
         -0.2808, -0.4701,  1.1725,  0.4892,  1.2253, -1.6260, -0.6900, -0.1836,
         -1.8120, -0.2896, -0.0439,  0.1404,  1.2037, -0.7312,  1.5238,  0.0416,
          1.1100,  1.8582,  

## 임베딩 벡터 리스트의 일부
* fasttext.en.300d
* fasttext.simple.300d
* glove.42B.300d
* glove.840B.300d
* glove.twitter.27B.25d
* glove.twitter.27B.50d
* glove.twitter.27B.100d
* glove.twitter.27B.200d
* glove.6B.50d
* glove.6B.100d
* glove.6B.200d
* glove.6B.300d <= 이걸 사용해볼 겁니다.

### IMDB 리뷰 데이터에 존재하는 단어들을 토치텍스트가 제공하는 사전 훈련된 임베딩 벡터들의 값으로 초기화해봅시다.

In [39]:
from torchtext.vocab import GloVe
TEXT.build_vocab(trainset, vectors=GloVe(name='6B', dim=300), max_size=10000, min_freq=10)
LABEL.build_vocab(trainset)

.vector_cache\glove.6B.zip: 862MB [11:04, 1.30MB/s]                           
100%|█████████▉| 399999/400000 [00:33<00:00, 11905.33it/s]


In [41]:
# print(TEXT.vocab.stoi)

In [42]:
print('임베딩 벡터의 개수와 차원 : {} '.format(TEXT.vocab.vectors.shape))

임베딩 벡터의 개수와 차원 : torch.Size([10002, 300]) 
