In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

model = nn.Sequential(
   nn.Linear(2, 1), # input_dim = 2, output_dim = 1
   nn.Sigmoid() # 출력은 시그모이드 함수를 거친다
)

print(model(x_train))

print(model)

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward>)
Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)


In [3]:
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = model(x_train)

    # cost 계산
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
        print('correct_prediction:',correct_prediction)
        print('correct_prediction.sum():',correct_prediction.sum())
        print('correct_prediction.sum().item() :',correct_prediction.sum().item())

        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

correct_prediction: tensor([[ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True]])
correct_prediction.sum(): tensor(5)
correct_prediction.sum().item() : 5
Epoch    0/1000 Cost: 0.539713 Accuracy 83.33%
correct_prediction: tensor([[ True],
        [ True],
        [ True],
        [False],
        [False],
        [ True]])
correct_prediction.sum(): tensor(4)
correct_prediction.sum().item() : 4
Epoch   10/1000 Cost: 0.614853 Accuracy 66.67%
correct_prediction: tensor([[ True],
        [ True],
        [False],
        [False],
        [ True],
        [ True]])
correct_prediction.sum(): tensor(4)
correct_prediction.sum().item() : 4
Epoch   20/1000 Cost: 0.441875 Accuracy 66.67%
correct_prediction: tensor([[ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True]])
correct_prediction.sum(): tensor(5)
correct_prediction.sum().item() : 5
Epoch   30/1000 Cost: 0.373145 Accuracy 83.33%
correct_prediction: tensor([[ Tr

In [4]:
model(x_train)

tensor([[2.7616e-04],
        [3.1595e-02],
        [3.8959e-02],
        [9.5624e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward>)

In [5]:
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2534, 1.5181]], requires_grad=True), Parameter containing:
tensor([-14.4839], requires_grad=True)]


위의 출력값이 nn.Module을 사용하지 않고 로지스틱 회귀를 구현한 실습에서 얻었던  w와 b와 거의 일치한다.