## 1.torch
tensor등의 다양한 수학 함수가 포함되어 있으며 numpy와 유사한 구조를 가진다. 

## 2.torch.autograd
자동 미분을 위한 함수들이 포함되어 있다. 

## 3.torch.nn
신경망을 구축하기 위한 다양한 데이터 구조나 레이어 등이 정의되어져 있다. 

## 4.torch.optim
SGD를 중심으로 한 파라미터 최적화 알고리즘의 구현되어 있다.

## 5.torch.utils.data
SGD의 반복 연산을 실행할 때 사용하는 미니 배치용 유틸리티 함수가 포함되어 있다. 

## 6.torch.onnx
ONNX(Open Neural Network Exchange)의 포맷으로 모델을 익스포트(export)할 때 사용한다. ONNX는 서로 다른 딥 러닝 프레임워크 간에 모델을 공유할 때 사용하는 포맷이다.

---
# 텐서 조작하기 1
  ## 벡터, 행렬, 텐서
    *스칼라 : 차원이 없는 값
    *벡터 : 1차원으로 구성된 값
    *행렬 : 2차원으로 구성된 값
    *텐서 : 3차원 이상
  ### 자연어 처리는 보통(batch size, 문장 길이, 단어 벡터의 차원)이라는 3차원 텐서를 사용한다.


In [17]:
# 넘파이로 텐서 만들기(벡터와 행렬 만들기)
import numpy as np

# 1D 
t = np.array([0,1,2,3,4,5,6])
print(t)
print(t.ndim)
print(t.shape)
print(t[0],t[1],t[-1])

[0 1 2 3 4 5 6]
1
(7,)
0 1 6


In [18]:
# 2D
t = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t)
print(t.ndim)
print(t.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [19]:
import torch

# 1D
t = torch.FloatTensor([0,1,2,3,4,5,6])
print(t)
print(t.dim()) # 차원
print(t.size()) # shape
print(t.shape) # shape 


tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [20]:
# 2D
t = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(t)
print(t.dim())
print(t.size())
print(t[:,1])  # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [21]:
# 브로드캐스팅(broadcasting)

# 두 행렬이 곱셈을 할 때는 a의 마지막 차원과 b의 첫번째 차원이 일치해야한다.
# 파이토치에서는 자동으로 크기를 맞춰서 연산을 수행하게 하는 브로드캐스팅 기능을 제공한다.

m1 = torch.FloatTensor([[3,3]]) 
m2 = torch.FloatTensor([[2,2]])

print(m1+m2)

# vector + scalar
m3 = torch.FloatTensor([[1,2]]) 
m4 = torch.FloatTensor([3])

print(m3+m4)

# 2 x 1 vector + 1 x 2 vector
m5 = torch.FloatTensor([[1,2]]) 
m6 = torch.FloatTensor([[3],[4]])

print(m5+m6)


# 브로드캐스팅은 자동으로 수행되므로 사용자는 나중에 원하는 결과가 나오지 않았더라도 
# 어디서 문제가 발생했는지 찾기가 굉장히 어려울 수 있다.

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [22]:

# 행렬 곱셈 : matmul()
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2))

# 원소 곱셈 :  mul() 또는 *
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

# 평균 : mean()
t = torch.FloatTensor([1, 2])
print(t.mean())

# dim = 0 : 행을 지우고 열만 남기는 것 (첫 번째 차원 의미)
# dim = 1 : 열을 지우고 행만 남기는 것 == dim = -1

# 덧셈 : sum()

# 최대(Max)는 원소의 최대값을 리턴하고, 아그맥스(ArgMax)는 최대값을 가진 인덱스를 리턴
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max(dim=0))  

# 3과 4의 인덱스는 [1, 1]

# max 또는 argmax만 리턴받고 싶다면 다음과 같이 리턴값에도 인덱스를 부여
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])
tensor(1.5000)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [24]:
# 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경 == reshape
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [26]:
# 스퀴즈(Squeeze) - 1인 차원을 제거
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

print(ft.squeeze())
print(ft.squeeze().shape)

# 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

print(ft.unsqueeze(0)) 
print(ft.unsqueeze(0).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [28]:
# concatenate : torch.cat([ ])
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

# torch.cat 어느 차원을 늘릴 것인지 인자로 줄 수 있다.

print(torch.cat([x, y], dim=0)) # 첫 번째 차원 늘리기
print(torch.cat([x, y], dim=1)) # 두 번째 차원 늘리기

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [30]:
# Stacking : torch.stack([])

x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))

print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [35]:
# 1로 채워진 텐서 : torch.ones_like() 
# 동일한 크기(shape)지만 1으로만 값이 채워진 텐서를 생성
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

print(torch.ones_like(x))

# 0으로 채워진 텐서 : torch.zeros_like() 
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [36]:
# 덮어쓰기 연산 : 연산 뒤에 _를 붙이면 기존의 값을 덮어쓰기 한다
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력


print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
