1강. tensor

In [13]:
# torch tensor는 numpy array와 사용법이 유사하다.
import torch
import numpy as np

x =  torch.empty(5,4)
print(x)
torch.ones(3,3)





tensor([[8.4490e-39, 9.5510e-39, 9.5510e-39, 9.9184e-39],
        [9.0000e-39, 1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39, 1.0561e-38],
        [1.0102e-38, 1.0010e-38, 1.1112e-38, 8.7245e-39],
        [9.6429e-39, 9.6429e-39, 8.7245e-39, 4.2246e-39]])


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.zeros(2)

tensor([0., 0.])

In [15]:
torch.rand(5,6)

tensor([[0.7573, 0.4188, 0.1837, 0.5062, 0.0551, 0.3329],
        [0.6427, 0.9595, 0.4389, 0.1492, 0.1499, 0.2973],
        [0.0313, 0.2066, 0.9509, 0.0708, 0.8306, 0.6028],
        [0.5258, 0.3165, 0.0503, 0.3101, 0.0712, 0.1228],
        [0.0581, 0.4615, 0.7382, 0.4153, 0.0476, 0.5274]])

In [21]:
l = [13,4]
r = np.array([4,58,7])

print(torch.tensor(l))
print(torch.tensor(r))

print(type(x))


tensor([13,  4])
tensor([ 4, 58,  7], dtype=torch.int32)
<class 'torch.Tensor'>


In [22]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)


tensor([[0.6389, 0.4169],
        [0.1655, 0.3278]])
tensor([[0.7822, 0.1166],
        [0.8025, 0.7455]])


In [23]:
x+y

tensor([[1.4211, 0.5335],
        [0.9681, 1.0733]])

In [24]:
y.add(x) #y에 x를 더한다

tensor([[1.4211, 0.5335],
        [0.9681, 1.0733]])

In [25]:
y.add_(x) # y에 x를 더하고  새로운 y값으로 대체한다
print(y)

tensor([[1.4211, 0.5335],
        [0.9681, 1.0733]])


In [27]:
print(y[1,1])
print(y[:,1])


tensor(1.0733)
tensor([0.5335, 1.0733])


In [28]:
x = torch.rand(8,8)
print(x)

tensor([[0.4990, 0.2535, 0.0017, 0.9767, 0.1002, 0.2762, 0.8473, 0.9397],
        [0.0417, 0.7058, 0.2550, 0.5025, 0.9031, 0.1021, 0.6747, 0.1749],
        [0.4995, 0.1272, 0.4877, 0.7931, 0.0407, 0.7332, 0.0142, 0.2224],
        [0.9293, 0.2455, 0.9357, 0.1446, 0.0116, 0.2799, 0.4572, 0.1917],
        [0.9501, 0.5288, 0.1228, 0.0547, 0.1054, 0.8870, 0.2596, 0.7117],
        [0.1761, 0.9533, 0.6364, 0.6193, 0.8034, 0.8078, 0.5277, 0.7475],
        [0.8804, 0.8387, 0.0806, 0.5340, 0.9953, 0.7716, 0.2911, 0.9563],
        [0.0187, 0.7827, 0.3927, 0.6297, 0.3338, 0.6807, 0.4119, 0.5600]])


In [29]:
# 텐서를 일렬로 변환하고 싶을 때, 예) cnn에서 fc계층으로 갈때 사용할 수 있다.
x.view(64)

tensor([0.4990, 0.2535, 0.0017, 0.9767, 0.1002, 0.2762, 0.8473, 0.9397, 0.0417,
        0.7058, 0.2550, 0.5025, 0.9031, 0.1021, 0.6747, 0.1749, 0.4995, 0.1272,
        0.4877, 0.7931, 0.0407, 0.7332, 0.0142, 0.2224, 0.9293, 0.2455, 0.9357,
        0.1446, 0.0116, 0.2799, 0.4572, 0.1917, 0.9501, 0.5288, 0.1228, 0.0547,
        0.1054, 0.8870, 0.2596, 0.7117, 0.1761, 0.9533, 0.6364, 0.6193, 0.8034,
        0.8078, 0.5277, 0.7475, 0.8804, 0.8387, 0.0806, 0.5340, 0.9953, 0.7716,
        0.2911, 0.9563, 0.0187, 0.7827, 0.3927, 0.6297, 0.3338, 0.6807, 0.4119,
        0.5600])

In [32]:
print(x.view(4,16))
print(x.view(-1,16))


tensor([[0.4990, 0.2535, 0.0017, 0.9767, 0.1002, 0.2762, 0.8473, 0.9397, 0.0417,
         0.7058, 0.2550, 0.5025, 0.9031, 0.1021, 0.6747, 0.1749],
        [0.4995, 0.1272, 0.4877, 0.7931, 0.0407, 0.7332, 0.0142, 0.2224, 0.9293,
         0.2455, 0.9357, 0.1446, 0.0116, 0.2799, 0.4572, 0.1917],
        [0.9501, 0.5288, 0.1228, 0.0547, 0.1054, 0.8870, 0.2596, 0.7117, 0.1761,
         0.9533, 0.6364, 0.6193, 0.8034, 0.8078, 0.5277, 0.7475],
        [0.8804, 0.8387, 0.0806, 0.5340, 0.9953, 0.7716, 0.2911, 0.9563, 0.0187,
         0.7827, 0.3927, 0.6297, 0.3338, 0.6807, 0.4119, 0.5600]])
tensor([[0.4990, 0.2535, 0.0017, 0.9767, 0.1002, 0.2762, 0.8473, 0.9397, 0.0417,
         0.7058, 0.2550, 0.5025, 0.9031, 0.1021, 0.6747, 0.1749],
        [0.4995, 0.1272, 0.4877, 0.7931, 0.0407, 0.7332, 0.0142, 0.2224, 0.9293,
         0.2455, 0.9357, 0.1446, 0.0116, 0.2799, 0.4572, 0.1917],
        [0.9501, 0.5288, 0.1228, 0.0547, 0.1054, 0.8870, 0.2596, 0.7117, 0.1761,
         0.9533, 0.6364, 0.6193, 0.8

In [34]:
y = x.numpy()
print(y)
print(type(y))

[[0.49901283 0.25345182 0.00168777 0.97673935 0.10015661 0.27616554
  0.8472641  0.93972343]
 [0.04173613 0.70576906 0.25496274 0.5024653  0.90310663 0.10207897
  0.6747167  0.17485774]
 [0.4994728  0.1272201  0.48769158 0.79308915 0.04073465 0.7331977
  0.01424664 0.22237116]
 [0.92927396 0.24545246 0.93568534 0.14463717 0.01158631 0.2799273
  0.45723444 0.1917094 ]
 [0.9500571  0.5287921  0.12280542 0.05474734 0.10537475 0.8869892
  0.25956655 0.7116694 ]
 [0.17613214 0.9533126  0.6364271  0.6193012  0.8033911  0.80781305
  0.5276995  0.74748194]
 [0.8804058  0.838684   0.08061689 0.53401035 0.9952555  0.7716059
  0.29114097 0.956347  ]
 [0.01865989 0.78266037 0.3927467  0.62974614 0.3337642  0.68074685
  0.41186237 0.5599951 ]]
<class 'numpy.ndarray'>


In [35]:
x = torch.ones(1)
print(x)

tensor([1.])


In [36]:
# 값을 뽑아낼 때 item 사용. 예) loss값 직접 뽑아내고 싶을 때 사용
x.item()


1.0