2. 변수 선언(+ 데이터 입력)

In [19]:
# 미분 자동적으로 계산하는 원리 확인
import torch
x = torch.ones(2,2, requires_grad=True) # 기본값은 False,  True로 하면 x에 관한 연산을 모두 추적하게 해준다
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


3. 모델 내 연산 예측값 산출

In [20]:
y = x+1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


4. 손실함수 계산
5. 손실 산출



In [21]:
z = 2*y**2
res = z.mean()

print(res)

tensor(8., grad_fn=<MeanBackward0>)


최적화 = 손실함수를 기준으로 각 변수마다 미분을 하는 것

In [22]:
#d(res)/dx_i
# res = z_1 +...z+4)/4
# z_i = 2 y_i**2
# z_i = 2(x_i+1**2)
res.backward()
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


In [ ]:
import torch.nn as nn
import torch.nn.functional as F